blank_issues_enabled: true
contact_links:
  - name: Adrish Support
    url: https://t.me/AdrishSupport
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://Adrish.tech/
    about: Documentation for getting started with bot.
